theme: jekyll-theme-minimal
title: Ann Rutt
logo: /images/test.jpg
description: I am an advocate for wholistic education, particularly in STEM where non-technical skills are also critical to success

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/acrutt
  - name: Values
    icon: <i class="fa-brands fa-linkedin"></i>
    link: ./values.md