theme: jekyll-theme-minimal
title: Ann Rutt
logo: /images/test.jpg
description: A personal website to learn more about Ann Rutt

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/acrutt
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: ./values.md
